/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef snowflake_CONSTANTS_H
#define snowflake_CONSTANTS_H

#include "snowflake_types.h"



class snowflakeConstants {
 public:
  snowflakeConstants();

};

extern const snowflakeConstants g_snowflake_constants;



#endif
