/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "snowflake_constants.h"



const snowflakeConstants g_snowflake_constants;

snowflakeConstants::snowflakeConstants() {
}



